name: 'Yandex.Cloud Object Storage Upload (S3)'
description: 'Deploy static website to Yandex Object Storage'
author: 'Konstantin Mamaev'

inputs:
  accessKeyId:
    description: 'Service account access key id'
    default: ''
    required: true
  secretAccessKey:
    description: 'Service account secret access key'
    default: ''
    required: true
  bucketName:
    description: 'Bucket name'
    default: ''
    required: true
  sourceDir:
    description: 'Path to upload folder'
    default: ''
    required: false
  include:
    description: 'Include patterns for files'
    required: false
  includeDots:
    description: 'Include dot files'
    default: false
    required: false
  exclude:
    description: 'Exclude patterns for files'
    required: false
  clear:
    description: 'Clear bucket before deploy'
    default: false
    required: false
  region:
    description: 'Bucket region'
    default: 'ru-central1-a'
    required: false

branding:
  color: blue
  icon: upload-cloud

runs:
  using: 'node16'
  main: 'dist/index.js'
